server:
  servlet:
    context-path: /community


#将thymeleaf的缓存关闭，但是在实际项目中是打开的。
spring:
  thymeleaf:
    cache: false
    #配置数据源信息
  datasource:
    password: root
    username: root
    url: jdbc:mysql:///community?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    username: 1725675802@qq.com
    password: xnhictybylkihhhb
    protocol: smtps
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        smtl:
          auth=true: true
  redis:
    database: 11
    host: localhost
    port: 6379
    timeout: 5000
    #password:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class:  org.quartz.simpl.SimpleThreadPool
            threadCount: 5
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5



#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcode.commuity.domain
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true #自动生成id

#设置日志级别
logging:
  level:
    com.nowcode.commuity: debug
  file:
    path: d:/code/work/data/nowcode/community.log
#配置插件助手
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql

commuity:
  path:
    domain: http://localhost:8080
  upload: d:/code/work/data/upload

elasticSearch:
  url: 127.0.0.1:9200

#Wk
wk:
  image:
    command: d:/code/work/wkhtmltopdf/bin/wkhtmltoimage
    storage: d:/code/work/data/wk-image

#qiniu
qiniu:
  key:
    access: -ymO9N3Y3ZDfGaZ1VEqDMtYt1Sb7hjp-KNfuAqWp
    secret: xDq8lKBlvwIxiUK1491xV1gFU8jYYhX2jTc472sv
  bucket:
    header:
      name: community2header2
      url: http://r4atjzvuk.hn-bkt.clouddn.com
    share:
      name: community2share2
      url: http://r4auraqrj.hn-bkt.clouddn.com
#caffeine
caffeine:
  posts:
    maxsize: 15
    expire-seconds: 180

#taskExecutionProperties


